In [1]:
import numpy as np
from numpy.linalg import norm

# Из методички 2

### 1. Найти скалярное произведение векторов $x, y \in \mathbb{R} :$  
a) $x=(0, -3, 6), y=(-4, 7, 9)$   
б) $x=(7, -4, 0, 1), y=(-3, 1, 11, 2)$

In [2]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print("a * b =", np.dot(x, y))

a * b = 33


In [3]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print("a * b =", np.dot(x, y))

a * b = -23


### 2. Найти нормы векторов  (4, 2, 4)  и  (12, 3, 4)  и угол между ними.

In [4]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

print('l1 a:',norm(a, ord=1))
print('l2 a:',norm(a, ord=2))

print('l1 b:',norm(b, ord=1))
print('l2 b:',norm(b, ord=2))

cos_phi = np.dot(a, b) / norm(a) / norm(b)
print('cos(ab):', '%.3f' % cos_phi)
print('angle(ab):', '%.3f' % np.arccos(cos_phi))

l1 a: 10.0
l2 a: 6.0
l1 b: 19.0
l2 b: 13.0
cos(ab): 0.897
angle(ab): 0.457


### 3. Будет ли линейное пространство евклидовым, если за скалярное произведение принять:
а) произведение длин векторов;   
б) утроенное обычное скалярное произведение векторов?

### 4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3} :$  
a) $(1, 0, 0), (0, 0, 1)$   
б) $(1 / \sqrt{2}, -1 / \sqrt{2}, 0), (1 / \sqrt{2}, 1 / \sqrt{2}, 0),(0, 0, 1) ;$   
B) $(1 / 2, -1 / 2, 0), (0, 1 / 2, 1 / 2), (0, 0, 1) ;$   
r) $(1, 0, 0), (0, 1, 0), (0, 0, 1) ?$

# Из методички 3

### 1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:  
  
а) A — матрица 4×2, B — матрица 4×2;  
б) A — матрица 2×5, B — матрица 5×3;  
в) A — матрица 8×3, B — матрица 3×8;  
г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.

In [5]:
def get_matrix_with_size(dim1, dim2):
    return np.empty([dim1, dim2])

а) A — матрица 4×2, B — матрица 4×2;  

In [6]:
a = get_matrix_with_size(4,2)
b = get_matrix_with_size(4,2)
a @ b

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

a) произведение матриц не определено

б) A — матрица 2×5, B — матрица 5×3; 

In [7]:
a = get_matrix_with_size(2,5)
b = get_matrix_with_size(5,3)
a @ b

array([[1.59779468e-054, 4.34760927e-122, 1.93604256e-058],
       [1.20299885e-053, 2.05938863e-122, 1.40199915e-058]])

In [8]:
(a @ b).shape

(2, 3)

б) произведение матриц определено, размерность полученной матрицы 2,3

в) A — матрица 8×3, B — матрица 3×8;  

In [9]:
a = get_matrix_with_size(8,3)
b = get_matrix_with_size(3,8)
a @ b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
(a @ b).shape

(8, 8)

в) произведение матриц определено, размерность полученной матрицы 8,8

г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.

In [11]:
a = get_matrix_with_size(4,4)
b = get_matrix_with_size(4,4)
a @ b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

г) произведение матриц определено, размерность полученной матрицы 4,4

### 2. Найти сумму и произведение матриц  
$A=\left(\begin{array}{cc}{1} & {-2} \\ {3} & {0}\end{array}\right)$ и $B=\left(\begin{array}{cc}{4} & {-1} \\ {0} & {5}\end{array}\right)$

In [12]:
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])

In [13]:
print("sum(AB):\n", a + b)

sum(AB):
 [[ 5 -3]
 [ 3  5]]


In [14]:
print("dot(AB):\n", a @ b)

dot(AB):
 [[  4 -11]
 [ 12  -3]]


### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство.   
Вычислить линейную комбинацию $3 A-2 B+4 C$ для матриц $A=\left(\begin{array}{cc}{1} & {7} \\ {3} & {-6}\end{array}\right), B=\left(\begin{array}{cc}{0} & {5} \\ {2} & {-1}\end{array}\right), C=\left(\begin{array}{cc}{2} & {-4} \\ {1} & {1}\end{array}\right)$

In [18]:
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])

In [19]:
3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

### 4. Дана матрица A. Вычислить $AA^{T}$ и $A^{T}A$  
$A=\left(\begin{array}{cc}{4} & {1} \\ {5} & {-2} \\ {2} & {3}\end{array}\right)$

In [22]:
a = np.array([[4,1],[5,-2],[2,3]])

In [27]:
a@a.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [28]:
a.T@a

array([[45,  0],
       [ 0, 14]])